---
# Common group vars
all:
  vars:
    ansible_ssh_private_key_file: "/home/toz/.ssh/id_ed25519" 
    ansible_become: true        
  # Groups
  children:
    linux-hosts:
      vars:
        ansible_user: toz
        ansible_password: 22tatara
        ansible_become_password: 22tatara
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      children:
        astra:
          children:
            astra176:
              hosts:
                astra176-1:
                  ansible_host: 192.168.4.23
                astra176-2:
                  ansible_host: 192.168.4.24
            astra181:
                hosts:
                  astra181-1:
                    ansible_host: 192.168.4.25
                  astra181-2:
                    ansible_host: 192.168.4.26
        mint:
          hosts:
            mint-1:
              ansible_host: 192.168.4.21
            mint-2:
              ansible_host: 192.168.4.22



# linux-temp:
#   vars:
#     ansible_user: toz
#     ansible_password: 22tatara
#     ansible_become_password: 22tatara
#     ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
#   hosts:
#     test-mint-1:
#       ansible_host: 192.168.4.178
#     test-alse-1:
#       ansible_host: 192.168.4.89
          
                                